### ISSUE TITLE
Read Aloud fails when injected helpers shadow Node.js module aliases

### ISSUE THREAD

**Issue by rysabh** [ilysenko/codex-desktop-linux#1445]
Read Aloud's speaker button turns red and produces no speech even when the Kokoro runtime and voice files are installed and speech generation works independently.

With `read-aloud` and `record-and-replay` enabled, `requireName(source, "node:path")` matches a function-local binding in an earlier injected helper instead of the top-level path module. An isolated test of the installed generated handler reproduces `TypeError: n.join is not a function`. Reusing that alias also causes `ReferenceError: Cannot access 'n' before initialization` in the settings-path helper.

This is the same class of scope problem as #898, which was fixed for `child_process`; the remaining filesystem, path, and OS bindings are still vulnerable.

The fix in `linux-features/read-aloud/patch.js` is to resolve these builtins directly, matching the existing `child_process` approach:

```js
const fsVar = "require(`node:fs`)";
const pathVar = "require(`node:path`)";
const osVar = "require(`node:os`)";
```

Remove the obsolete null checks for these three expressions. Leave the Electron binding logic unchanged.

Regression coverage in `linux-features/read-aloud/test.js` includes the actual Record & Replay helper, earlier nested module aliases, and local-name collisions. These cases fail before the fix and pass afterward. The related Read Aloud, Read Aloud MCP, and Record & Replay suites pass all 113 tests. Signed-package builds with Read Aloud alone and with the combined features also pass. After rebuilding, installing, and restarting, the user confirmed Read Aloud works.

This fix was generated by Codex.

**Comment by ilysenko** [comment]
Thank you for the report. I am investigating this now.
